# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1e9a2c8be060ca849a58bf1d40658167b3fe0f860230fa0976c697f7158ee6b5a297c0b648849a0947cba38fb25847345ee3be900b5090e5f4f4dd7b55b6fe2

test:
  secret_key_base: f6aa02104ca7a2d31a87ecbb44f812eb448469d9c1e2ed7cf9f62deb4a7850afa0cf9b570f65876bf522b6d686a2e1b9e3d5c339cde0993a6ac59ad28eaab8ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
